# Matrix
https://docs.scipy.org/doc/numpy/user/numpy-for-matlab-users.html
> Given the above, we intend to deprecate matrix eventually.



In [1]:
import numpy as np

In [2]:
a = np.matrix('1 2; 3 4')
a

matrix([[1, 2],
        [3, 4]])

In [3]:
b = np.matrix('5 6; 7 8')
b

matrix([[5, 6],
        [7, 8]])

In [4]:
a.T

matrix([[1, 3],
        [2, 4]])

In [5]:
a*b

matrix([[19, 22],
        [43, 50]])

In [6]:
b*a

matrix([[23, 34],
        [31, 46]])

In [7]:
a.T*b

matrix([[26, 30],
        [38, 44]])

In [20]:
v1= np.matrix('1; 2')
v1

matrix([[1],
        [2]])

In [21]:
v2= np.matrix('3; 4')

In [22]:
v1.T*v2

matrix([[11]])

In [23]:
v2.T*v1

matrix([[11]])

In [24]:
v1*v2.T

matrix([[3, 4],
        [6, 8]])

In [25]:
v2*v1.T

matrix([[3, 6],
        [4, 8]])

In [26]:
np.matrix(np.eye(2))

matrix([[ 1.,  0.],
        [ 0.,  1.]])

In [27]:
np.matrix(np.ones([2,2]))

matrix([[ 1.,  1.],
        [ 1.,  1.]])

In [28]:
np.matrix(np.zeros([2,2]))

matrix([[ 0.,  0.],
        [ 0.,  0.]])

In [29]:
a.I

matrix([[-2. ,  1. ],
        [ 1.5, -0.5]])